dict_to_save['name_col_x_tab0'] = self.view.x_var_var.get()
dict_to_save['name_col_y_tab_0'] = self.view.y_var.get()
dict_to_save['name_serial_var'] = self.view.name_serial_var.get()
dict_to_save['polynom_degree'] = self.view.polynominal_degree.get()
dict_to_save['step_value'] = self.view.step.get()
dict_to_save['scope_down_entry_tab0'] = self.view.total_down_scope_var.get()
dict_to_save['scope_up_entry_tab0'] = self.view.total_up_scope_var.get()
dict_to_save['formula_x'] = self.view.x_math_form.get()
dict_to_save['formula_y'] = self.view.y_math_form.get()
dict_to_save['time_tag'] = self.view.time_var_tab1.get()
dict_to_save['column_x_tag_tab1'] = self.view.self.y1_var_tab1.get()
dict_to_save['column_y_tag_tab1'] = self.view.y2_var_tab1.get()
dict_to_save['down_scope_tab1'] = self.view.down_scope_var_tab_1.get()
dict_to_save['up_scope_tab_1'] = self.view.up_scope_var_tab_1.get()
dict_to_save['scale_time_chart'] = self.view.up_scope_var_tab_1.get()
dict_to_save['name_of_chart'] = self.view.name_of_chart_var.get()
dict_to_save['name_of_X_axis_tab3'] = self.view.name_of_X_axis_var.get()
dict_to_save['unit_of_X_axis_tab3'] = self.view.unit_of_X_axis_var.get()
dict_to_save['name_of_Y_axis_tab3'] = self.view.name_of_Y_axis_var.get()
dict_to_save['unit_of_Y_axis_tab3'] = self.view.unit_of_Y_axis_var.get()



